version: "3.9"
services: 
  app: 
    build:
      context: .
      target: app
    links:
    - postgres
    environment:
      MIX_ENV: '${MIX_ENV:-dev}'

  e2e:
    build:
      context: .
      target: e2e
    links:
    - postgres
    environment:
      MIX_ENV: '${MIX_ENV:-test}'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallaby_example_${MIX_ENV:-dev}
