version: "3.9"
services: 
  app: 
    build:
      context: .
      target: test
    links:
    - postgres

  e2e:
    build:
      context: .
      target: e2e
    links:
    - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallaby_example_dev
