version: "3.9"
services: 
  app: 
    build: .
    links:
    - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallaby_example_dev
